name: topfuelauto_mobile
description: TopFuel Auto mobile MVP
version: 0.1.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  dio: ^5.4.2
  flutter_secure_storage: ^9.2.2

flutter:
  uses-material-design: true